import Head from 'next/head'
import Image from 'next/image'
import Header from "../Components/Header";
import Nav from "../Components/Nav";
import Results from "../Components/Results";
import request from "../utils/request";

export default function Home({data, res}) {
     console.log(data);


  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-[#06202a] text-gray-300">
        <Header/>
        <Nav/>
        <Results results={data} />
      </body>
      
    </div>
  )
};

export async function getServerSideProps(context){
    const res = await fetch(`https://api.themoviedb.org/3/${request.Trending.url}`)
    const data = await res.json();

  
    if(!data){
        return {
            notFound: true,
        }
    }

    return {
        props : {data, res}
    }
}


// export async function getServerSideProps(context){
//   const genre = context.query.genre;
//
//   const request = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.trending.url} `)
//       .then(res => res.json )
//
//   return{
//       props:{
//           results: request.results,
//       },
//   }
//
// }
