import Head from 'next/head'
import Image from 'next/image'
import Header from "../Components/Header";
import Nav from "../Components/Nav";
import Results from "../Components/Results";
import request from "../utils/request";

export default function Home(props) {
    console.log(props);

  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <Nav/>
        <Results />
    </div>
  )
};

export async function getServerSideProp(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3/${request[genre]?.url || request.trending.url} `)
      .then(res => res.json )

  return{
      props:{
          results: request.results,
      },
  }

}
